### PR TITLE
notify all matching channels

### LINKED ISSUE #53: regression: multi-channel notifications no longer working
this commit
https://github.com/pragbits/stash2slack/commit/b0c4c65cb137914ef5f866f1f0e215c0a11378b9

removed the ability to notify to multiple channels.

perhaps you could just remove the `break;` statement when looping over the pattern+channel pairs?
https://github.com/pragbits/stash2slack/commit/b0c4c65cb137914ef5f866f1f0e215c0a11378b9#diff-7a7a86b6ef70500ad62811622eb9e598R324

### PR DESCRIPTION
**Pull request by paulcichonski**
Fixes #53

### CODE REVIEW

**Comment by ebukoski** [comment]
@pragbits Any chance we can get this PR merged?

**Comment by boldwade** [comment]
Is this PR dead? Could we get this merged?

**Comment by yadsweb** [comment]
+4

**Comment by tracymazelin** [comment]
+1 for merging this PR so we can notify multiple channels

**Comment by leonkyr** [comment]
Closing as this was implemented in master now.

**Pull request closed without merging**
